# Generated by Django 5.2.10 on 2026-03-28 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_alter_message_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='readers',
            field=models.ManyToManyField(related_name='read_msgs', to=settings.AUTH_USER_MODEL),
        ),
    ]
