# Generated by Django 5.2.10 on 2026-04-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_message_readers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageimage',
            name='image',
        ),
        migrations.AddField(
            model_name='messageimage',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messageimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messageimage',
            name='public_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messageimage',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='messageimage',
            name='width',
            field=models.IntegerField(),
        ),
    ]
