# Generated by Django 5.2.10 on 2026-04-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_remove_messageimage_image_messageimage_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
