from django.urls import path
from .views import *

urlpatterns = [
    path('settings/<int:profile_id>', view=render_profile_settings, name='profile_settings'),
    path('albums/<int:profile_id>', view=render_albums, name='albums'),
    path('albums/add-photo', view=add_photo, name='add_photo'),
    path('albums/delete-photo/<int:photo_id>', view=delete_photo, name='delete_photo'),
    path('albums/create-album', view=create_album, name='create_album'),
    path('albums/update-album/<int:album_id>', view=update_album, name='update_album'),
    path('albums/delete-album/<int:album_id>', view=delete_album, name='delete_album'),
    path('albums/toggle-album/<int:album_id>', view=toggle_album, name='toggle_album'),
    path('albums/toggle-photo/<int:photo_id>', view=toggle_photo, name='toggle_photo'),
    path('settings/update-credentials', view=update_credentials, name='update_credentials'),
    path('settings/update-password', view=update_passwords, name='update_password'),
    path('settings/update-signature', view=update_signature, name='update_signature'),
    path('settings/update-personal-data', view=update_personal_data, name='update_personal_data'),
    path('settings/username-available', view=check_username, name='username_available'),
    path('settings/email-verification/start', view=start_email_verification, name='start'),
    path('settings/email-verification/verify', view=verify_email_code, name='verify'),
    path('settings/email-verification/cancel', view=cancel_email_verification, name='cancel'),
    path('friends/all', view=render_friends, name='friends'),
    path('friends', view=render_friends_all, name='friends_all'),
    path('friends/requests', view=render_friends_requests, name='friends_requests'),
    path('friends/recommendation', view=render_friends_recommendation, name='friends_recommendation'),
    path('friends/accept-friend-request/<int:id>', view=accept_friends_request, name='friends-accept'),
    path('friends/cancel-friend-request/<int:id>', view=cancel_friends_request, name='friends-cancel'),
    path('friends/add-friend/<int:id>', view=add_friend, name='friends_add'),
    path('friends/remove-friend/<int:id>', view=remove_friend, name='friends_remove'),
    path('<int:profile_id>', view=render_profile, name='profile_page'),
]