# Generated by Django 5.2.10 on 2026-02-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0006_album_is_special_alter_album_theme_alter_album_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
