# Generated by Django 5.2.10 on 2026-02-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0007_profile_pseudonym'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='is_special',
            new_name='is_default',
        ),
    ]
