# Generated by Django 5.2.10 on 2026-02-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0009_alter_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='avatar',
        ),
    ]
