# Generated by Django 5.2.10 on 2026-02-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0010_rename_photo_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='photo',
        ),
    ]
