# Generated by Django 5.2.10 on 2026-02-17 18:07

import profile_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0011_rename_avatar_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimage',
            name='image',
            field=models.ImageField(upload_to=profile_app.models.upload_image),
        ),
    ]
