# Generated by Django 5.2.10 on 2026-02-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0012_alter_albumimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimage',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='albumimage',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
