# Generated by Django 5.2.10 on 2026-03-10 14:34

import profile_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0014_album_created_at_albumimage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimage',
            name='image',
            field=models.ImageField(height_field='height', upload_to=profile_app.models.upload_image, width_field='width'),
        ),
    ]
