# Generated by Django 5.2.10 on 2026-01-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='signature',
            field=models.ImageField(null=True, upload_to='profiles/signature'),
        ),
    ]
