# Generated by Django 5.2.10 on 2026-01-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_profile_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
