# Generated by Django 5.2.10 on 2026-01-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_emailverification_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_image_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_text_signature',
            field=models.BooleanField(default=False),
        ),
    ]
