# Generated by Django 5.2.10 on 2026-02-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_profile_is_image_signature_profile_is_text_signature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
