# Generated by Django 5.2.10 on 2026-02-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_alter_post_options_post_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
