# Generated by Django 5.2.10 on 2026-03-11 12:42

import post_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0006_postview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(height_field='height', upload_to=post_app.models.upload_image, width_field='width'),
        ),
    ]
